name: Run Bash Command

on: [push]

jobs:
  run_bash_command:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a bash script
        run: |
          echo "Hello, world!"
          echo "Running a bash command."
          sudo systemctl status chronyd.service
          sudo systemctl restart chronyd.service
          sudo cat /etc/passwd
